# Here are all the packages you'll need for the course.
# If you don't have a package installed, you can install it using
# install.packages("package_name")

library(ggplot2)
library(magrittr)
library(dplyr)
library(readxl)
library(caret)
library(pROC)
library(PRROC)
library(stargazer)
library(haven)
library(GGally)
library(gridExtra)
library(glmnet)
library(mgcv)
library(plotly)
library(abess)
library(e1071)
library(xgboost)
library(randomForest)
library(randomForestExplainer)
library(class)
library(ddpcr)
library(tidyr)
library(ggrepel)
library(knitr)
library(ggthemes)
library(readr)
library(quanteda)
library(tm)
library(xtable)
library(scales)